title: <p align="center"> Balamurugan Portfolio </p>
logo: <p align="center"> /assets/img/bala.jpg </p>
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/balamurugan-gnanasekaran-australian-pr-holder-6bb0bb17/">LinkedIn</a>
  <a href="https://github.com/balamurugan1979">GitHub</a>  
  <br>   
  <br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
