title: <p align="center"> Balamurugan Portfolio </p>
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/balamurugan-gnanasekaran-australian-pr-holder-6bb0bb17/">LinkedIn</a> |
  <a href="https://github.com/balamurugan1979">GitHub</a>
  
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>

show_downloads: true
google_analytics:

theme: jekyll-theme-minimal

